import { KlipperConfigHelper } from '@/server/helpers/klipper-config';
import { PrinterConfiguration } from '@/zods/printer-configuration';
import { maybeRenderBeaconOverrides } from '@/templates/helpers/beacon';
import { VAOCControlPoints } from '@/server/helpers/config-generation/ratrig-vaoc';

export const template = async (config: PrinterConfiguration, helper: KlipperConfigHelper) => {
	const vaocControlPoints: VAOCControlPoints = {
		xcontrolpoint: config.size.x / 2 - 37.5,
		ycontrolpoint: config.size.y + 30.5,
		zcontrolpoint: 10,
		zoffsetcontrolpoint: 0,
	};
	return `
# WARNING. THIS FILE IS GENERATED BY THE RATOS CONFIGURATOR.
# CHANGES YOU MAKE HERE WILL BE OVERWRITTEN. KEEP YOUR CHANGES IN PRINTER.CFG.
# Config generated for ${config.printer.manufacturer} ${config.printer.name} ${config.size.x}
# Documentation: https://os.ratrig.com

#############################################################################################################
### CONTROLBOARD & TOOLBOARD
#############################################################################################################
${helper.renderBoards()}

#############################################################################################################
### BASE SETUP
#############################################################################################################
${helper.renderBase()}
[include RatOS/printers/uboe-tenor/uboe-tenor.cfg]
[include RatOS/printers/uboe-tenor/macros.cfg]
[include RatOS/printers/uboe-tenor/${config.size.x}.cfg]

# Extruder
${helper.renderExtruder()}

# Hotend
${helper.renderHotend()}

# ADXL345 resonance testing configuration
${helper.renderInputShaper(config.size)}

#############################################################################################################
### STEPPER MOTORS, DRIVERS & SPEED LIMITS
#############################################################################################################
${helper.renderMotorSections()}
${helper.renderSpeedLimits()}
variable_macro_z_speed: ${Math.round(config.printer.speedLimits.basic.z_velocity / 2)}

[bed_mesh]
speed: 300
probe_count: 9,9

[quad_gantry_level]
speed: 300

#############################################################################################################
### HOMING
#############################################################################################################
${helper.renderProbeIncludes()}
${maybeRenderBeaconOverrides(config, {
	proximityMargins: { left: 20, right: 20, top: 20, bottom: 20 },
	contactMargins: { left: 20, right: 20, top: 20, bottom: 20 },
	enableAdaptiveHeatsoak: true,
})}
${helper.renderEndstopSection()}

#############################################################################################################
### FANS
#############################################################################################################
${helper.renderFans()}

#############################################################################################################
### ACCESSORIES
#############################################################################################################
${await helper.renderToolheadAlignmentSystemHardwareAsync()}

${await helper.renderFilamentSensorsAsync()}

${await helper.renderChamberLightingAsync()}

${await helper.renderChamberAirFilterAsync()}

#############################################################################################################
### MACRO CONFIGURATION
#############################################################################################################
${helper.renderMacros()}

[gcode_macro T0]
variable_has_oozeguard: True

[gcode_macro T1]
variable_has_oozeguard: True

# Macro variable overrides
[gcode_macro RatOS]
${helper.renderMacroVariableOverrides()}
variable_home_y_first: True

# Save variables
${helper.renderSaveVariables(vaocControlPoints)}

[gcode_macro _VAOC]
variable_expected_camera_x_position: ${vaocControlPoints.xcontrolpoint}
variable_expected_camera_y_position: ${vaocControlPoints.ycontrolpoint}
`;
};

export const initialPrinterCfg = (config: PrinterConfiguration, helper: KlipperConfigHelper) => `
#############################################################################################################
### CONFIGURATION GENERATED BY THE RATOS CONFIGURATOR
### Everything below [include RatOS.cfg] will override default RatOS behavior
#############################################################################################################
[include RatOS.cfg]

#############################################################################################################
### MACRO CONFIGURATION
### Configure the behavior of RatOS macros
### See: https://os.ratrig.com/docs/configuration/macros
#############################################################################################################
[gcode_macro RatOS]
variable_relative_extrusion: True
variable_preheat_extruder: True
variable_calibrate_bed_mesh: True
variable_nozzle_priming: "primeblob"
variable_start_print_park_in: "back"
variable_start_print_park_z_height: 50
variable_end_print_park_in: "back"
variable_pause_print_park_in: "back"

#############################################################################################################
### USER OVERRIDES & CUSTOM CONFIGURATION
### Anything custom you want to add, or RatOS configuration you want to override, do it here.
### See: https://os.ratrig.com/docs/configuration/includes-and-overrides
#############################################################################################################
`;
