import path from 'path';
import { existsSync, readFileSync } from 'fs';
import { serverSchema } from '@/env/schema.mjs';
import { replaceOrAddIniSectionsFromFileSync } from '@/server/helpers/file-operations';

export function getUpdatedCrowsnestConfigurationForVaoc() {
	const environment = serverSchema.parse(process.env);
	const crowsnestPath = path.join(environment.KLIPPER_CONFIG_PATH, 'crowsnest.conf');
	return replaceOrAddIniSectionsFromFileSync(crowsnestPath, [
		{
			section: 'crowsnest',
			body: `log_path: /home/pi/printer_data/logs/crowsnest.log
log_level: verbose
delete_log: false
no_proxy: false
`,
		},
		{
			section: 'cam 1',
			body: `# Required for Rat Rig VAOC camera integration, DO NOT MODIFY THIS SECTION.
mode: camera-streamer
enable_rtsp: false
rtsp_port: 8554
port: 8080
device: /dev/video0
resolution: 1920x1080
max_fps: 30
`,
		},
	]);
}

export type VAOCControlPoints = {
	xcontrolpoint?: number;
	ycontrolpoint?: number;
	zcontrolpoint?: number;
	zoffsetcontrolpoint?: number;
};

export function getVaocControlPointVariables(config: { size: { x: number } }, options?: VAOCControlPoints): string[] {
	return [
		`idex_applied_offset = 1`,
		`idex_xcontrolpoint = ${options?.xcontrolpoint ?? config.size.x / 2}`,
		`idex_xoffset = 0.0`,
		`idex_ycontrolpoint = ${options?.ycontrolpoint ?? 50}`,
		`idex_yoffset = 0.0`,
		`idex_zcontrolpoint = ${options?.zcontrolpoint ?? 50}`,
		`idex_zoffset = 0.0`,
		`idex_zoffsetcontrolpoint = ${options?.zoffsetcontrolpoint ?? 25}`,
	];
}

export function getDcEndstopConfigurationFileContent(forceDefault: boolean): string {
	const environment = serverSchema.parse(process.env);
	const configPath = path.join(environment.KLIPPER_CONFIG_PATH, 'dc_endstop.cfg');
	if (forceDefault || !existsSync(configPath)) {
		return `# WARNING. THIS FILE IS GENERATED BY THE RATOS CONFIGURATOR
# AND UPDATED BY THE CALCULATE_DC_ENDSTOP MACRO.
# DO NOT DELETE OR MODIFY THIS FILE.

[gcode_macro CALCULATE_DC_ENDSTOP]
variable_config_generated: False
`;
	}
	return readFileSync(configPath, 'utf-8');
}
